apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-ai-deployment
  labels:
    app: chess-ai
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chess-ai
  template:
    metadata:
      labels:
        app: chess-ai
    spec:
      containers:
        - image: ghcr.io/seoulsky/chess-ai/ai:latest
          imagePullPolicy: Always
          name: ai
          ports:
          - containerPort: 81
        - image: ghcr.io/seoulsky/chess-ai/web:latest
          imagePullPolicy: Always
          name: web
          ports:
          - containerPort: 80
